dependencies:
  build:
    - android:latest
    - java:8.202.08
    - gradle:5.4.1
build_targets:
  - name: default
    root: WHACKProject
    commands:
      - sdkmanager --install tools
      - sdkmanager --install platform-tools
      - sdkmanager --install build-tools;23.0.2
      - sdkmanager --install platforms;android-23
      - sdkmanager --install system-images;android-23;default;x86_64
      - ./gradlew clean test
ci:
  builds:
    - name: android_build
      build_target: default
